### ISSUE TITLE
Unix (X11): In GHCi, input behaves weird after calling `setClipboardString`

### ISSUE THREAD

**Issue by Daniel-Diaz** [Daniel-Diaz/Clipboard#4]
To reproduce, I do the following:

    ? stack ghci
    *System.Clipboard> setClipboardString "something"
    *System.Clipboard> a

Then you get a ``Not in scope``-error (expected), and the input starts not showing up, or showing up wrong (not expected).

I didn't try ``cabal repl`` yet, but I would expect the same result.

Pinging @mat8913

**Comment by mat8913** [comment]
I think this may be caused by a clipboard manager. Clipboard managers wait for other applications to take control of the clipboard, then request the clipboard contents and take control of the clipboard themselves. In other words, the clipboard manager is taking control of the clipboard immediately after the forked process does. I didn't notice this issue earlier because I normally don't have a clipboard manager installed (I run a fairly minimal setup due to old hardware).
